// All site copy lives here — edit freely.
export type Lang = "en" | "ar";

export const contact = {
  whatsapp: "962782328748",
  phone: "+962 7 8232 8748",
  email: "quantomlap@gmail.com",
  instagram: "https://www.instagram.com/q.lap_26",
  instagramHandle: "@q.lap_26",
};

const en = {
  nav: {
    about: "About",
    software: "Software",
    ai: "AI",
    arduino: "Arduino",
    courses: "Courses",
    projects: "Projects",
    contact: "Contact",
  },
  hero: {
    tag: "Software · AI · Arduino · Education",
    title1: "We engineer",
    title2: "intelligent things.",
    sub: "Quantum builds software, trains AI, wires hardware and teaches the next generation of makers — all under one signal.",
    cta: "Start a project",
    cta2: "Explore",
    stats: [
      { n: 500, s: "+", l: "Students trained" },
      { n: 17, s: "", l: "Courses" },
      { n: 20, s: "+", l: "Projects" },
    ],
  },
  about: {
    kicker: "01 / About",
    title: "Where code meets circuits.",
    body: "Quantum is a technology lab that turns ideas into working systems. We write the software, design the intelligence, build the hardware — and teach others how to do the same.",
    vision: "Vision",
    visionText: "A region where every curious mind can build with code, AI and electronics.",
    mission: "Mission",
    missionText: "Deliver reliable tech solutions and hands-on education that create real makers.",
    pillars: ["Software", "AI", "Arduino", "Education"],
  },
  software: {
    kicker: "02 / Software Solutions",
    title: "Code, compiled into products.",
    sub: "Hover a service to see how we build it.",
    items: [
      {
        name: "Web Development",
        desc: "Fast, modern websites and web platforms.",
        code: [
          "const site = await build({",
          "  stack: 'react', seo: true,",
          "  speed: 'blazing'",
          "});",
          "deploy(site); // ✓ live",
        ],
      },
      {
        name: "Mobile Apps",
        desc: "Cross-platform iOS & Android apps.",
        code: [
          "app.target(['ios','android'])",
          "app.ui.adapt('every-screen')",
          "app.sync({ offline: true })",
          "store.publish(app)",
          "// ✓ shipped",
        ],
      },
      {
        name: "Custom Software",
        desc: "Systems tailored to how your business works.",
        code: [
          "class Workflow {",
          "  automate(tasks) {",
          "    return tasks.map(optimize)",
          "  }",
          "} // hours → minutes",
        ],
      },
      {
        name: "Dashboards & APIs",
        desc: "Data, integrations and admin tools.",
        code: [
          "GET /api/insights",
          "→ 200 OK",
          "{ revenue: '+38%',",
          "  users: 12480 }",
          "// realtime ✓",
        ],
      },
    ],
  },
  ai: {
    kicker: "03 / AI Solutions",
    title: "Intelligence, wired in.",
    sub: "Move your cursor over the network — every node is a capability.",
    items: [
      { name: "Chatbots & Assistants", desc: "Smart assistants trained on your data." },
      { name: "Computer Vision", desc: "Detection, recognition and visual inspection." },
      { name: "Predictive Analytics", desc: "Models that forecast demand and behavior." },
      { name: "Process Automation", desc: "AI agents that handle repetitive work." },
      { name: "Edge AI", desc: "Machine learning running on tiny devices." },
    ],
  },
  arduino: {
    kicker: "04 / Arduino & Hardware",
    title: "Hardware that comes alive.",
    sub: "Boards, kits, sensors and AI modules available at Quantum. Tap any item to ask about it.",
    ask: "Ask about this product",
    whatsapp: "WhatsApp",
    contactUs: "Contact us",
    available: "Available in store",
    close: "Close",
    waMsg: "Hi Quantum, I'd like to ask about: ",
    boardHint: "Hover or tap the board — every component tells you what it does.",
    hotspots: [
      { k: "usb", t: "USB Port", d: "Upload your code and power the board from any computer." },
      { k: "power", t: "Power Jack", d: "Run projects standalone on a 7–12V supply." },
      {
        k: "mcu",
        t: "Microcontroller",
        d: "The brain: an ATmega328P running your program 16 million times a second.",
      },
      {
        k: "digital",
        t: "Digital Pins",
        d: "14 input/output pins for LEDs, buttons, motors and relays.",
      },
      {
        k: "analog",
        t: "Analog Inputs",
        d: "6 inputs that read sensors like temperature, light and sound.",
      },
      {
        k: "led",
        t: "Status LEDs",
        d: "Built-in lights that blink with your very first line of code.",
      },
    ],
    products: [
      {
        key: "board",
        name: "Arduino Uno R3",
        cat: "Board",
        desc: "The classic ATmega328P board — the perfect start for any electronics project.",
        specs: ["ATmega328P · 16 MHz", "14 digital / 6 analog pins", "USB-B programming"],
      },
      {
        key: "kit",
        name: "Starter Sensor Kit",
        cat: "Kit",
        desc: "Ultrasonic sensor, servo, LEDs, resistors, breadboard and jumper wires.",
        specs: ["30+ components", "Beginner project guide", "Works with Uno & Nano"],
      },
      {
        key: "cam",
        name: "ESP32-CAM AI Module",
        cat: "AI Module",
        desc: "Wi-Fi camera board for computer vision and edge AI experiments.",
        specs: ["OV2640 2MP camera", "Wi-Fi + Bluetooth", "Face & object detection"],
      },
      {
        key: "robot",
        name: "Smart Robot Car Kit",
        cat: "Robotics",
        desc: "4-wheel robot with obstacle avoidance and line tracking, ready to program.",
        specs: ["4 DC motors + driver", "Ultrasonic & line sensors", "Bluetooth app control"],
      },
    ],
    inventoryTitle: "Components in stock",
    inventorySub: "Sensors, modules and parts for every build — tap any part to ask about it.",
    groups: [
      {
        name: "Sensors",
        items: [
          { k: "hcsr04", n: "HC-SR04 Ultrasonic", s: "2–400 cm range" },
          { k: "dht22", n: "DHT22 Temp & Humidity", s: "±0.5 °C accuracy" },
          { k: "pir", n: "HC-SR501 PIR Motion", s: "Up to 7 m detection" },
          { k: "mq2", n: "MQ-2 Gas & Smoke", s: "LPG, smoke, CO" },
          { k: "soil", n: "Capacitive Soil Moisture", s: "Corrosion-resistant" },
          { k: "ldr", n: "LDR Light Sensor", s: "Analog + digital out" },
        ],
      },
      {
        name: "Boards & AI",
        items: [
          { k: "nano", n: "Arduino Nano", s: "ATmega328P · compact" },
          { k: "mega", n: "Arduino Mega 2560", s: "54 digital I/O pins" },
          { k: "esp32", n: "ESP32 DevKit", s: "Wi-Fi + Bluetooth" },
          { k: "esp8266", n: "ESP8266 NodeMCU", s: "Wi-Fi IoT board" },
          { k: "huskylens", n: "AI Vision Camera", s: "Face & object recognition" },
          { k: "pico", n: "Raspberry Pi Pico", s: "RP2040 · dual-core" },
        ],
      },
      {
        name: "Motors & Actuators",
        items: [
          { k: "sg90", n: "SG90 Micro Servo", s: "180° · 1.8 kg·cm" },
          { k: "mg996r", n: "MG996R Metal Servo", s: "Metal gears · 11 kg·cm" },
          { k: "stepper", n: "28BYJ-48 Stepper + Driver", s: "With ULN2003 board" },
          { k: "l298n", n: "L298N Motor Driver", s: "Dual H-bridge · 2 A" },
          { k: "relay", n: "5V Relay Module", s: "Switch up to 10 A" },
          { k: "buzzer", n: "Active Buzzer", s: "5V sound alerts" },
        ],
      },
      {
        name: "Display & Power",
        items: [
          { k: "oled", n: '0.96" OLED I2C', s: "128×64 pixels" },
          { k: "lcd", n: "16×2 LCD + I2C", s: "Blue backlight" },
          { k: "ws2812", n: "WS2812B RGB Strip", s: "Addressable · 60 LED/m" },
          { k: "18650", n: "18650 Battery Holder", s: "2-cell · 7.4 V" },
          { k: "breadboard", n: "Breadboard 830", s: "Solderless prototyping" },
          { k: "jumpers", n: "Jumper Wires Set", s: "M-M · M-F · F-F" },
        ],
      },
    ],
  },
  courses: {
    kicker: "05 / Courses & Training",
    title: "A learning path, not a list.",
    sub: "Follow the signal from your first line of code to building intelligent devices.",
    level: "Level",
    weeks: "weeks",
    ask: "Ask about this course",
    waMsg: "Hi Quantum, I'm interested in the course: ",
    start: "START",
    finish: "YOU BUILD IT",
    items: [
      {
        name: "Python",
        desc: "The most versatile language in tech — scripting, automation, data and backend development.",
        w: 8,
        lvl: "Beginner",
      },
      {
        name: "Web Development",
        desc: "Modern front-end and back-end craft — responsive interfaces, APIs and full-stack deployment.",
        w: 10,
        lvl: "Beginner",
      },
      {
        name: "Arduino",
        desc: "Microcontroller programming, circuits and embedded systems — build real, physical, connected devices.",
        w: 6,
        lvl: "Beginner",
      },
      {
        name: "Artificial Intelligence",
        desc: "Machine learning foundations, deep learning and generative AI systems from first principles to production.",
        w: 14,
        lvl: "Advanced",
      },
      {
        name: "Robotics",
        desc: "Design, build and program autonomous robots — sensors, actuators, kinematics and control systems.",
        w: 12,
        lvl: "Advanced",
      },
    ],
    catalogTitle: "All 17 courses",
    catalogSub:
      "Every course is a full learning path — from fundamentals to deployable, portfolio-ready projects.",
    all: "All",
    cats: [
      { k: "ai", n: "AI & ML" },
      { k: "xr", n: "XR / VR / AR" },
      { k: "engines", n: "Engines & Games" },
      { k: "hardware", n: "Arduino & Robotics" },
      { k: "programming", n: "Programming" },
      { k: "webdesign", n: "Web & Design" },
      { k: "secdata", n: "Security & Data" },
    ],
    catalog: [
      {
        cat: "ai",
        name: "Artificial Intelligence",
        desc: "Machine learning foundations, deep learning and generative AI systems from first principles to production.",
        w: 14,
        lvl: "Advanced",
      },
      {
        cat: "ai",
        name: "Machine Learning",
        desc: "Supervised and unsupervised learning, model evaluation and real-world data pipelines that ship.",
        w: 12,
        lvl: "Advanced",
      },
      {
        cat: "xr",
        name: "XR Development",
        desc: "Design cross-reality experiences that blend the physical and digital across every immersive platform.",
        w: 10,
        lvl: "Intermediate",
      },
      {
        cat: "xr",
        name: "VR Development",
        desc: "Build fully immersive virtual worlds with real-time engines, spatial audio and 3D interaction systems.",
        w: 10,
        lvl: "Intermediate",
      },
      {
        cat: "xr",
        name: "AR Development",
        desc: "Overlay digital intelligence onto the real world with mobile AR, spatial tracking and marker recognition.",
        w: 8,
        lvl: "Intermediate",
      },
      {
        cat: "engines",
        name: "Unity",
        desc: "Build cross-platform 2D and 3D games and interactive experiences with the industry's most-used engine.",
        w: 8,
        lvl: "Beginner",
      },
      {
        cat: "engines",
        name: "Unreal Engine",
        desc: "Push AAA-grade visuals with Blueprints and C++ — lighting, physics and high-fidelity real-time rendering.",
        w: 10,
        lvl: "Intermediate",
      },
      {
        cat: "hardware",
        name: "Arduino",
        desc: "Microcontroller programming, circuits and embedded systems — build real, physical, connected devices.",
        w: 6,
        lvl: "Beginner",
      },
      {
        cat: "hardware",
        name: "Robotics",
        desc: "Design, build and program autonomous robots — sensors, actuators, kinematics and control systems.",
        w: 12,
        lvl: "Advanced",
      },
      {
        cat: "programming",
        name: "Python",
        desc: "The most versatile language in tech — scripting, automation, data and backend development.",
        w: 8,
        lvl: "Beginner",
      },
      {
        cat: "programming",
        name: "C#",
        desc: "Object-oriented programming for games, apps and enterprise software built on the .NET ecosystem.",
        w: 8,
        lvl: "Beginner",
      },
      {
        cat: "programming",
        name: "C++",
        desc: "High-performance programming for systems, engines and real-time applications where speed matters.",
        w: 10,
        lvl: "Intermediate",
      },
      {
        cat: "engines",
        name: "Game Development",
        desc: "Game engines, 3D pipelines and gameplay systems — ship playable titles from concept to release.",
        w: 12,
        lvl: "Intermediate",
      },
      {
        cat: "webdesign",
        name: "Web Development",
        desc: "Modern front-end and back-end craft — responsive interfaces, APIs and full-stack deployment.",
        w: 10,
        lvl: "Beginner",
      },
      {
        cat: "webdesign",
        name: "UI/UX Design",
        desc: "Design systems, wireframing and user research — craft interfaces people genuinely enjoy using.",
        w: 6,
        lvl: "Beginner",
      },
      {
        cat: "secdata",
        name: "Cyber Security",
        desc: "Threat modeling, network defense and ethical hacking — protect systems the way attackers think.",
        w: 12,
        lvl: "Advanced",
      },
      {
        cat: "secdata",
        name: "Data Science",
        desc: "Statistics, visualization and predictive modeling — turn raw data into decisions that matter.",
        w: 12,
        lvl: "Advanced",
      },
    ],
  },
  faq: {
    kicker: "FAQ",
    title: "Questions, answered.",
    sub: "Everything people usually ask before joining a course.",
    more: "Still have a question?",
    moreSub: "Our admissions team replies on WhatsApp — just send us a message.",
    moreBtn: "Ask on WhatsApp",
    topics: [
      { k: "courses", n: "Courses" },
      { k: "registration", n: "Registration" },
      { k: "certificates", n: "Certificates" },
      { k: "schedule", n: "Schedule" },
      { k: "fees", n: "Fees" },
      { k: "online", n: "Online learning" },
    ],
    items: [
      {
        topic: "courses",
        q: "What courses does Quantum offer?",
        a: "17 courses across AI, XR/VR/AR, Unity, Unreal Engine, Arduino, Robotics, Python, C#, C++, Game Development, Web Development, UI/UX, Cyber Security and Data Science.",
      },
      {
        topic: "courses",
        q: "Do I need prior experience to start a course?",
        a: "No prior experience is required for our foundational tracks. Each course starts from first principles, and applicants are placed into the right starting level after a short skills assessment.",
      },
      {
        topic: "registration",
        q: "How do I register for a course?",
        a: "Message us on WhatsApp or through the contact page with your course of interest, or email us directly. Our admissions team will follow up within 1–2 business days to confirm your seat.",
      },
      {
        topic: "registration",
        q: "Can I switch tracks after enrolling?",
        a: "Yes, within the first two weeks of a cohort you can switch tracks at no extra cost, subject to seat availability.",
      },
      {
        topic: "certificates",
        q: "Do I receive a certificate after graduating?",
        a: "Yes. Every graduate receives a Quantum certification plus a reviewed project portfolio you can share with employers.",
      },
      {
        topic: "certificates",
        q: "Are Quantum certificates recognized by employers?",
        a: "Our certificates are backed by a reviewed project portfolio and a hiring partner network, which is what employers weigh most alongside the credential itself.",
      },
      {
        topic: "schedule",
        q: "How long are the courses?",
        a: "Most tracks run 10–14 weeks part-time, with intensive full-time options available that compress the same curriculum into 5–6 weeks.",
      },
      {
        topic: "schedule",
        q: "Are classes in-person, online, or both?",
        a: "Both. Hardware-heavy tracks like Robotics and Arduino are strongly recommended in-person for lab access, while AI, Programming and Game Development are available fully online with live mentor sessions.",
      },
      {
        topic: "fees",
        q: "How much do courses cost?",
        a: "Tuition varies by track and format — contact our admissions team for current pricing and any active cohort offers.",
      },
      {
        topic: "fees",
        q: "Are payment plans available?",
        a: "Yes, monthly installment plans are available for every track, along with need-based scholarships for eligible students.",
      },
      {
        topic: "online",
        q: "What do I need for online learning?",
        a: "A laptop and stable internet connection are enough for most software tracks. Hardware tracks include a starter kit shipped to you as part of enrollment.",
      },
      {
        topic: "online",
        q: "Is online learning as effective as in-person?",
        a: "Online cohorts follow the same curriculum with live mentor sessions, code/project reviews and career support — the format changes, the rigor doesn't.",
      },
    ],
  },
  projects: {
    kicker: "06 / Projects",
    title: "Selected work.",
    items: [
      {
        k: "greenhouse",
        name: "Smart Greenhouse",
        tag: "IoT · Arduino",
        meta: "2025 · Jordan Valley",
        desc: "Soil and climate sensors that water and ventilate automatically — cutting water use by 35%.",
      },
      {
        k: "clinic",
        name: "Clinic Booking Platform",
        tag: "Web App",
        meta: "2025 · Amman",
        desc: "Online appointments, reminders and an admin dashboard for a multi-doctor clinic.",
      },
      {
        k: "vision",
        name: "Retail Vision Counter",
        tag: "Computer Vision",
        meta: "2024 · Amman",
        desc: "An AI camera that counts visitors in real time and reports peak hours.",
      },
      {
        k: "chatbot",
        name: "Campus Assistant Bot",
        tag: "AI Chatbot",
        meta: "2024 · Irbid",
        desc: "Answers student questions about schedules and services around the clock.",
      },
      {
        k: "robots",
        name: "Line-Follower Robots",
        tag: "Education",
        meta: "2025 · Zarqa",
        desc: "A school robotics program — 40 students built and raced their own robots.",
      },
    ],
  },
  why: {
    kicker: "07 / Why Quantum",
    title: "Four reasons, one signal.",
    items: [
      { t: "End-to-end", d: "From idea to code to hardware — one team handles everything." },
      { t: "Hands-on training", d: "Every course is built around real projects you can hold." },
      { t: "Real support", d: "We stay with you after delivery, not just until launch." },
      { t: "Practical AI", d: "AI that solves actual problems, not demos." },
    ],
  },
  contact: {
    kicker: "08 / Contact",
    title: "Send us a signal.",
    sub: "Have a project, a product question or want to join a course? We reply fast.",
    name: "Your name",
    email: "Email",
    message: "Message",
    send: "Send message",
    sent: "Thanks! We'll get back to you soon.",
    viaWhatsapp: "Or send it on WhatsApp",
    errName: "Please enter your name.",
    errEmail: "Please enter a valid email.",
    errMessage: "Tell us a bit more (10+ characters).",
    waHello: "Hello Quantum Lab, I would like to know more about your courses.",
    location: "Amman, Jordan",
    labels: {
      whatsapp: "WhatsApp",
      phone: "Phone",
      email: "Email",
      instagram: "Instagram",
      location: "Location",
    },
    follow: "Follow our lab on Instagram",
    followSub: "Builds, workshops and new hardware — first on Instagram.",
  },
  home: {
    marquee: [
      "Software",
      "Artificial Intelligence",
      "Arduino",
      "Courses",
      "IoT",
      "Computer Vision",
      "Robotics",
      "Web & Mobile",
    ],
    process: {
      kicker: "HOW WE BUILD",
      title: "From a spark to a running system.",
      sub: "Every Quantum project travels the same five-stage circuit — so you always know what comes next.",
      steps: [
        {
          t: "Discover",
          d: "We listen, visit the site and map the real problem before writing a single line.",
        },
        { t: "Design", d: "Wireframes, circuit sketches and a clear plan with timeline and cost." },
        { t: "Build", d: "Code, train and solder in short sprints — you see progress every week." },
        { t: "Launch", d: "Real-world testing, deployment and hands-on training for your team." },
        { t: "Support", d: "Monitoring, updates and a team that answers when you call." },
      ],
    },
    showcase: {
      kicker: "FEATURED WORK",
      title: "Built here. Running out there.",
      sub: "A few of the systems we designed, coded and wired — now working every day.",
      all: "See all projects",
    },
    numbers: {
      kicker: "BY THE NUMBERS",
      title: "Six years of signal.",
      items: [
        { n: 500, s: "+", l: "Students trained" },
        { n: 17, s: "", l: "Courses" },
        { n: 20, s: "+", l: "Projects" },
        { n: 95, s: "%", l: "Student satisfaction" },
      ],
    },
    voices: {
      kicker: "WHAT PEOPLE SAY",
      title: "Voices from the circuit.",
      items: [
        {
          q: "The Robotics and Arduino track completely changed how I approach engineering — labs felt like working at a real startup.",
          n: "Rania Malik",
          r: "Robotics Track Graduate",
        },
        {
          q: "I went from zero to shipping a VR prototype in twelve weeks. The mentorship here is unmatched.",
          n: "Karim Taha",
          r: "XR/VR Track Graduate",
        },
        {
          q: "Quantum Lab's AI program is as rigorous as any bootcamp I've seen — and the career support actually delivered.",
          n: "Sara Lund",
          r: "AI Track Graduate",
        },
        {
          q: "The Unity and Game Development track took my side-project idea and turned it into a real, finished game.",
          n: "Daniel Osei",
          r: "Game Development Graduate",
        },
        {
          q: "Cyber Security here is hands-on from day one — I was running real penetration tests within the first month.",
          n: "Nadia Fares",
          r: "Cyber Security Graduate",
        },
      ],
    },
    outro: {
      words: ["Code.", "Circuits.", "Intelligence."],
      sub: "Three disciplines, one lab. Step inside and meet the people behind the signal.",
      btn: "Meet the lab",
    },
  },
  pages: {
    home: "Home",
    app: {
      tabs: { home: "Home", software: "Software", ai: "AI", arduino: "Arduino" },
      more: "More",
      menu: "Menu",
      language: "Language",
      quick: "Quick contact",
      call: "Call",
      close: "Close",
    },
    lost: {
      title: "Signal lost.",
      sub: "This page doesn't exist or has moved. Let's get you back on the circuit.",
      btn: "Back to home",
    },
    next: "NEXT PAGE",
    loading: "ROUTING SIGNAL",
    explore: {
      kicker: "EXPLORE QUANTUM",
      title: "Seven worlds, one lab.",
      sub: "Every part of Quantum has its own page — pick a door and step in.",
      enter: "Enter",
    },
    cta: {
      title: "Got an idea? Let's wire it up.",
      sub: "Software, AI, a smart device or a course — tell us what you want to build.",
      btn: "Start a project",
      alt: "Message on WhatsApp",
    },
    about: {
      title: "A lab where ideas get built.",
      sub: "Who we are, what drives us, and why makers and businesses trust Quantum.",
      blurb: "Our story, vision and the reasons people work with us.",
      facts: [
        { n: 4, s: "", l: "Disciplines under one roof" },
        { n: 6, s: "+", l: "Years of building" },
        { n: 15, s: "+", l: "Engineers & trainers" },
      ],
    },
    software: {
      title: "Software that ships.",
      sub: "Websites, apps and custom systems — engineered for speed and built to last.",
      blurb: "Web, mobile, custom systems, dashboards and APIs.",
      facts: [
        { n: 70, s: "+", l: "Apps & sites launched" },
        { n: 99, s: "%", l: "Uptime on hosted projects" },
        { n: 4, s: "", l: "Core service lines" },
      ],
    },
    ai: {
      title: "AI that does real work.",
      sub: "Chatbots, computer vision and prediction — practical intelligence for real problems.",
      blurb: "Chatbots, vision, prediction, automation and edge AI.",
      facts: [
        { n: 25, s: "+", l: "AI models deployed" },
        { n: 5, s: "", l: "AI capabilities" },
        { n: 24, s: "/7", l: "Assistants always on" },
      ],
    },
    arduino: {
      title: "The hardware corner.",
      sub: "Boards, kits, sensors and AI modules — come see them, ask about them, build with them.",
      blurb: "Boards, kits, sensors and AI modules in store.",
      facts: [
        { n: 60, s: "+", l: "Items in stock" },
        { n: 24, s: "", l: "Component types" },
        { n: 4, s: "", l: "Featured kits" },
      ],
    },
    courses: {
      title: "Learn by building.",
      sub: "A clear path from your first line of code to your own smart device.",
      blurb: "17 courses in AI, XR, games, Arduino, programming, web and security.",
      facts: [
        { n: 500, s: "+", l: "Students trained" },
        { n: 17, s: "", l: "Courses" },
        { n: 7, s: "", l: "Learning tracks" },
      ],
    },
    projects: {
      title: "Work that's out in the world.",
      sub: "Real systems running in farms, clinics, shops and schools across Jordan.",
      blurb: "Real builds for farms, clinics, shops and schools.",
      facts: [
        { n: 20, s: "+", l: "Projects" },
        { n: 5, s: "", l: "Cities served" },
        { n: 35, s: "%", l: "Water saved by one build" },
      ],
    },
    contact: {
      title: "Let's talk.",
      sub: "WhatsApp, call, email or drop by the lab — we reply fast.",
      blurb: "WhatsApp, phone, email, Instagram and location.",
      facts: [
        { n: 1, s: "h", l: "Typical reply time" },
        { n: 7, s: "", l: "Days a week on WhatsApp" },
        { n: 95, s: "%", l: "Student satisfaction" },
      ],
    },
  },
  footer: {
    tagline:
      "A technology lab building software, AI and hardware — and teaching the makers of tomorrow.",
    explore: "EXPLORE",
    connect: "CONNECT",
    rights: "All rights reserved.",
    top: "Back to top",
  },
};

const ar: typeof en = {
  nav: {
    about: "من نحن",
    software: "البرمجيات",
    ai: "الذكاء الاصطناعي",
    arduino: "أردوينو",
    courses: "الدورات",
    projects: "أعمالنا",
    contact: "تواصل",
  },
  hero: {
    tag: "برمجيات · ذكاء اصطناعي · أردوينو · تعليم",
    title1: "نصنع",
    title2: "أشياءً ذكية.",
    sub: "في Quantum نطوّر البرمجيات، ونبني حلول الذكاء الاصطناعي، ونصمّم العتاد الإلكتروني، ونعلّم الجيل القادم من المبتكرين — كل ذلك في مكان واحد.",
    cta: "ابدأ مشروعك",
    cta2: "اكتشف المزيد",
    stats: [
      { n: 500, s: "+", l: "متدرب" },
      { n: 17, s: "", l: "دورة" },
      { n: 20, s: "+", l: "مشروع" },
    ],
  },
  about: {
    kicker: "٠١ / من نحن",
    title: "حيث يلتقي الكود بالدوائر.",
    body: "Quantum مختبر تقني يحوّل الأفكار إلى أنظمة تعمل فعلًا. نكتب البرمجيات، ونصمّم الذكاء، ونبني العتاد — ونعلّم غيرنا كيف يفعلون ذلك.",
    vision: "رؤيتنا",
    visionText: "منطقة يستطيع فيها كل شغوف أن يبتكر بالكود والذكاء الاصطناعي والإلكترونيات.",
    mission: "رسالتنا",
    missionText: "تقديم حلول تقنية موثوقة وتعليم عملي يصنع مبتكرين حقيقيين.",
    pillars: ["البرمجيات", "الذكاء الاصطناعي", "أردوينو", "التعليم"],
  },
  software: {
    kicker: "٠٢ / الحلول البرمجية",
    title: "كود يتحوّل إلى منتجات.",
    sub: "مرّر المؤشر على أي خدمة لترى كيف نبنيها.",
    items: [
      {
        name: "تطوير المواقع",
        desc: "مواقع ومنصات ويب حديثة وسريعة.",
        code: en.software.items[0]!.code,
      },
      {
        name: "تطبيقات الجوال",
        desc: "تطبيقات iOS وAndroid بتجربة سلسة.",
        code: en.software.items[1]!.code,
      },
      {
        name: "برمجيات مخصّصة",
        desc: "أنظمة مصمّمة على مقاس طريقة عملك.",
        code: en.software.items[2]!.code,
      },
      {
        name: "لوحات التحكم والـAPI",
        desc: "بيانات وتكاملات وأدوات إدارة.",
        code: en.software.items[3]!.code,
      },
    ],
  },
  ai: {
    kicker: "٠٣ / حلول الذكاء الاصطناعي",
    title: "ذكاءٌ متّصل بكل شيء.",
    sub: "حرّك المؤشر فوق الشبكة — كل عقدة تمثّل قدرة جديدة.",
    items: [
      { name: "روبوتات المحادثة", desc: "مساعدون أذكياء مدرَّبون على بياناتك." },
      { name: "الرؤية الحاسوبية", desc: "كشف وتعرّف وفحص بصري آلي." },
      { name: "التحليلات التنبؤية", desc: "نماذج تتوقّع الطلب والسلوك." },
      { name: "أتمتة العمليات", desc: "وكلاء ذكاء اصطناعي ينجزون المهام المتكررة." },
      { name: "الذكاء على الأجهزة", desc: "تعلّم آلي يعمل على أجهزة صغيرة." },
    ],
  },
  arduino: {
    kicker: "٠٤ / أردوينو والعتاد",
    title: "عتادٌ ينبض بالحياة.",
    sub: "لوحات وحقائب تعليمية وحساسات ووحدات ذكاء اصطناعي متوفرة لدى Quantum. اضغط على أي قطعة للاستفسار عنها.",
    ask: "استفسر عن هذا المنتج",
    whatsapp: "واتساب",
    contactUs: "تواصل معنا",
    available: "متوفر في المتجر",
    close: "إغلاق",
    waMsg: "مرحبًا Quantum، أودّ الاستفسار عن: ",
    boardHint: "مرّر المؤشر أو اضغط على اللوحة — كل قطعة تخبرك بوظيفتها.",
    hotspots: [
      { k: "usb", t: "منفذ USB", d: "ارفع برنامجك وشغّل اللوحة مباشرةً من أي حاسوب." },
      { k: "power", t: "مدخل الطاقة", d: "شغّل مشروعك باستقلالية عبر مصدر طاقة 7–12 فولت." },
      {
        k: "mcu",
        t: "المتحكم الدقيق",
        d: "عقل اللوحة: معالج ATmega328P ينفّذ برنامجك 16 مليون مرة في الثانية.",
      },
      {
        k: "digital",
        t: "المنافذ الرقمية",
        d: "14 منفذ إدخال وإخراج للّيدات والأزرار والمحركات والمرحّلات.",
      },
      {
        k: "analog",
        t: "المداخل التناظرية",
        d: "6 مداخل لقراءة الحساسات مثل الحرارة والضوء والصوت.",
      },
      { k: "led", t: "ليدات الحالة", d: "أضواء مدمجة تومض مع أول سطر برمجي تكتبه." },
    ],
    products: [
      {
        key: "board",
        name: "Arduino Uno R3",
        cat: "لوحة تحكم",
        desc: "اللوحة الكلاسيكية بمعالج ATmega328P — البداية المثالية لأي مشروع إلكتروني.",
        specs: ["ATmega328P · 16 MHz", "14 منفذًا رقميًا و6 تناظرية", "برمجة عبر USB-B"],
      },
      {
        key: "kit",
        name: "حقيبة الحساسات للمبتدئين",
        cat: "حقيبة",
        desc: "حساس مسافة، محرك سيرفو، LEDs، مقاومات، لوحة تجارب وأسلاك توصيل.",
        specs: ["أكثر من 30 قطعة", "دليل مشاريع للمبتدئين", "متوافقة مع Uno وNano"],
      },
      {
        key: "cam",
        name: "وحدة ESP32-CAM",
        cat: "وحدة ذكاء اصطناعي",
        desc: "لوحة كاميرا بشبكة Wi-Fi لتجارب الرؤية الحاسوبية والذكاء على الأجهزة.",
        specs: ["كاميرا OV2640 بدقة 2MP", "Wi-Fi وبلوتوث", "تعرّف على الوجوه والأجسام"],
      },
      {
        key: "robot",
        name: "حقيبة السيارة الروبوتية",
        cat: "روبوتات",
        desc: "روبوت بأربع عجلات يتفادى العوائق ويتتبّع الخطوط، جاهز للبرمجة.",
        specs: ["4 محركات مع وحدة تحكم", "حساسات مسافة وتتبّع خط", "تحكم عبر تطبيق بلوتوث"],
      },
    ],
    inventoryTitle: "قطع متوفرة لدينا",
    inventorySub: "حساسات ووحدات وقطع لكل مشروع — اضغط على أي قطعة للاستفسار عنها.",
    groups: [
      {
        name: "الحساسات",
        items: [
          { k: "hcsr04", n: "حساس المسافة HC-SR04", s: "مدى من 2 حتى 400 سم" },
          { k: "dht22", n: "حساس الحرارة والرطوبة DHT22", s: "دقة ±0.5 درجة" },
          { k: "pir", n: "حساس الحركة PIR", s: "كشف حتى 7 أمتار" },
          { k: "mq2", n: "حساس الغاز والدخان MQ-2", s: "غاز، دخان، أول أكسيد الكربون" },
          { k: "soil", n: "حساس رطوبة التربة", s: "مقاوم للتآكل" },
          { k: "ldr", n: "حساس الضوء LDR", s: "خرج تناظري ورقمي" },
        ],
      },
      {
        name: "اللوحات والذكاء الاصطناعي",
        items: [
          { k: "nano", n: "Arduino Nano", s: "ATmega328P · حجم صغير" },
          { k: "mega", n: "Arduino Mega 2560", s: "54 منفذًا رقميًا" },
          { k: "esp32", n: "ESP32 DevKit", s: "Wi-Fi وبلوتوث" },
          { k: "esp8266", n: "ESP8266 NodeMCU", s: "لوحة إنترنت الأشياء" },
          { k: "huskylens", n: "كاميرا الرؤية الذكية", s: "تعرّف على الوجوه والأجسام" },
          { k: "pico", n: "Raspberry Pi Pico", s: "معالج RP2040 ثنائي النواة" },
        ],
      },
      {
        name: "المحركات والمشغّلات",
        items: [
          { k: "sg90", n: "محرك سيرفو SG90", s: "180° · 1.8 كغ·سم" },
          { k: "mg996r", n: "محرك سيرفو MG996R", s: "تروس معدنية · 11 كغ·سم" },
          { k: "stepper", n: "محرك خطوي 28BYJ-48", s: "مع لوحة تحكم ULN2003" },
          { k: "l298n", n: "وحدة تحكم المحركات L298N", s: "قناتان · 2 أمبير" },
          { k: "relay", n: "وحدة ريليه 5V", s: "تتحكم حتى 10 أمبير" },
          { k: "buzzer", n: "صفّارة إلكترونية", s: "تنبيهات صوتية 5V" },
        ],
      },
      {
        name: "الشاشات والطاقة",
        items: [
          { k: "oled", n: "شاشة OLED مقاس 0.96 إنش", s: "دقة 128×64" },
          { k: "lcd", n: "شاشة LCD 16×2 مع I2C", s: "إضاءة خلفية زرقاء" },
          { k: "ws2812", n: "شريط ليد RGB نوع WS2812B", s: "قابل للبرمجة · 60 ليد/م" },
          { k: "18650", n: "حامل بطاريات 18650", s: "خليتان · 7.4 فولت" },
          { k: "breadboard", n: "لوحة تجارب 830 نقطة", s: "تجارب بدون لحام" },
          { k: "jumpers", n: "طقم أسلاك توصيل", s: "ذكر-ذكر · ذكر-أنثى · أنثى-أنثى" },
        ],
      },
    ],
  },
  courses: {
    kicker: "٠٥ / الدورات والتدريب",
    title: "مسار تعلّم، لا مجرد قائمة.",
    sub: "اتبع الإشارة من أول سطر كود حتى بناء أجهزة ذكية بنفسك.",
    level: "المستوى",
    weeks: "أسابيع",
    ask: "استفسر عن الدورة",
    waMsg: "مرحبًا Quantum، أنا مهتم بدورة: ",
    start: "البداية",
    finish: "تبني بنفسك",
    items: [
      {
        name: "بايثون",
        desc: "اللغة الأكثر مرونة في التقنية — البرمجة النصية والأتمتة والبيانات وتطوير الواجهة الخلفية.",
        w: 8,
        lvl: "مبتدئ",
      },
      {
        name: "تطوير الويب",
        desc: "حرفية حديثة للواجهة الأمامية والخلفية — واجهات متجاوبة، وواجهات برمجية، ونشر متكامل.",
        w: 10,
        lvl: "مبتدئ",
      },
      {
        name: "أردوينو",
        desc: "برمجة المتحكمات الدقيقة والدوائر والأنظمة المدمجة — ابنِ أجهزة حقيقية ومتصلة.",
        w: 6,
        lvl: "مبتدئ",
      },
      {
        name: "الذكاء الاصطناعي",
        desc: "أساسيات التعلم الآلي والتعلم العميق وأنظمة الذكاء الاصطناعي التوليدي من المبادئ الأولى إلى الإنتاج.",
        w: 14,
        lvl: "متقدم",
      },
      {
        name: "الروبوتات",
        desc: "صمم وابنِ وبرمج روبوتات ذاتية الحركة — أجهزة استشعار، ومشغلات، وحركية، وأنظمة تحكم.",
        w: 12,
        lvl: "متقدم",
      },
    ],
    catalogTitle: "جميع الدورات الـ17",
    catalogSub: "كل دورة مسار تعلّم كامل — من الأساسيات حتى مشاريع جاهزة للنشر وتُضاف لملف أعمالك.",
    all: "الكل",
    cats: [
      { k: "ai", n: "الذكاء الاصطناعي" },
      { k: "xr", n: "الواقع الممتد" },
      { k: "engines", n: "المحركات والألعاب" },
      { k: "hardware", n: "أردوينو وروبوتات" },
      { k: "programming", n: "البرمجة" },
      { k: "webdesign", n: "الويب والتصميم" },
      { k: "secdata", n: "الأمن والبيانات" },
    ],
    catalog: [
      {
        cat: "ai",
        name: "الذكاء الاصطناعي",
        desc: "أساسيات التعلم الآلي والتعلم العميق وأنظمة الذكاء الاصطناعي التوليدي من المبادئ الأولى إلى الإنتاج.",
        w: 14,
        lvl: "متقدم",
      },
      {
        cat: "ai",
        name: "التعلم الآلي",
        desc: "التعلم الموجّه وغير الموجّه، وتقييم النماذج، ومسارات بيانات واقعية جاهزة للإنتاج.",
        w: 12,
        lvl: "متقدم",
      },
      {
        cat: "xr",
        name: "تطوير الواقع الممتد",
        desc: "صمّم تجارب واقع متعدد تمزج بين المادي والرقمي عبر كل منصة غامرة.",
        w: 10,
        lvl: "متوسط",
      },
      {
        cat: "xr",
        name: "تطوير الواقع الافتراضي",
        desc: "ابنِ عوالم افتراضية غامرة بالكامل باستخدام محركات الزمن الحقيقي والصوت المكاني وأنظمة التفاعل ثلاثية الأبعاد.",
        w: 10,
        lvl: "متوسط",
      },
      {
        cat: "xr",
        name: "تطوير الواقع المعزز",
        desc: "أضِف ذكاءً رقميًا فوق العالم الحقيقي عبر الواقع المعزز على الجوال، وتتبع مكاني، والتعرف على العلامات.",
        w: 8,
        lvl: "متوسط",
      },
      {
        cat: "engines",
        name: "يونيتي",
        desc: "ابنِ ألعابًا وتجارب تفاعلية ثنائية وثلاثية الأبعاد عبر المنصات باستخدام المحرك الأكثر استخدامًا في الصناعة.",
        w: 8,
        lvl: "مبتدئ",
      },
      {
        cat: "engines",
        name: "أنريل إنجن",
        desc: "حقق مرئيات بمستوى AAA باستخدام Blueprints وC++ — إضاءة وفيزياء وعرض عالي الدقة في الزمن الحقيقي.",
        w: 10,
        lvl: "متوسط",
      },
      {
        cat: "hardware",
        name: "أردوينو",
        desc: "برمجة المتحكمات الدقيقة والدوائر والأنظمة المدمجة — ابنِ أجهزة حقيقية ومتصلة.",
        w: 6,
        lvl: "مبتدئ",
      },
      {
        cat: "hardware",
        name: "الروبوتات",
        desc: "صمم وابنِ وبرمج روبوتات ذاتية الحركة — أجهزة استشعار، ومشغلات، وحركية، وأنظمة تحكم.",
        w: 12,
        lvl: "متقدم",
      },
      {
        cat: "programming",
        name: "بايثون",
        desc: "اللغة الأكثر مرونة في التقنية — البرمجة النصية والأتمتة والبيانات وتطوير الواجهة الخلفية.",
        w: 8,
        lvl: "مبتدئ",
      },
      {
        cat: "programming",
        name: "سي شارب",
        desc: "برمجة كائنية التوجه للألعاب والتطبيقات والبرمجيات المؤسسية المبنية على منظومة .NET.",
        w: 8,
        lvl: "مبتدئ",
      },
      {
        cat: "programming",
        name: "سي بلس بلس",
        desc: "برمجة عالية الأداء للأنظمة والمحركات والتطبيقات في الزمن الحقيقي حيث تُحسب كل ميلي ثانية.",
        w: 10,
        lvl: "متوسط",
      },
      {
        cat: "engines",
        name: "تطوير الألعاب",
        desc: "محركات الألعاب ومسارات ثلاثية الأبعاد وأنظمة اللعب — أطلق ألعابًا قابلة للعب من الفكرة إلى الإصدار.",
        w: 12,
        lvl: "متوسط",
      },
      {
        cat: "webdesign",
        name: "تطوير الويب",
        desc: "حرفية حديثة للواجهة الأمامية والخلفية — واجهات متجاوبة، وواجهات برمجية، ونشر متكامل.",
        w: 10,
        lvl: "مبتدئ",
      },
      {
        cat: "webdesign",
        name: "تصميم واجهات وتجربة المستخدم",
        desc: "أنظمة تصميم، وتصميم أولي، وأبحاث المستخدم — صمّم واجهات يستمتع الناس فعليًا باستخدامها.",
        w: 6,
        lvl: "مبتدئ",
      },
      {
        cat: "secdata",
        name: "الأمن السيبراني",
        desc: "نمذجة التهديدات، والدفاع عن الشبكات، والاختراق الأخلاقي — احمِ الأنظمة بعقلية المهاجم.",
        w: 12,
        lvl: "متقدم",
      },
      {
        cat: "secdata",
        name: "علم البيانات",
        desc: "الإحصاء والتصوير البياني والنمذجة التنبؤية — حوّل البيانات الخام إلى قرارات مهمة.",
        w: 12,
        lvl: "متقدم",
      },
    ],
  },
  faq: {
    kicker: "أسئلة شائعة",
    title: "أسئلتكم، وإجاباتنا.",
    sub: "كل ما يسأل عنه الناس عادةً قبل الانضمام إلى دورة.",
    more: "عندك سؤال ثاني؟",
    moreSub: "فريق القبول بيرد عليك على واتساب — بس ابعتلنا رسالة.",
    moreBtn: "اسأل على واتساب",
    topics: [
      { k: "courses", n: "الدورات" },
      { k: "registration", n: "التسجيل" },
      { k: "certificates", n: "الشهادات" },
      { k: "schedule", n: "المواعيد" },
      { k: "fees", n: "الرسوم" },
      { k: "online", n: "التعلم عن بُعد" },
    ],
    items: [
      {
        topic: "courses",
        q: "ما هي الدورات التي تقدمها كوانتوم؟",
        a: "17 دورة في الذكاء الاصطناعي، والواقع الممتد/الافتراضي/المعزز، ويونيتي، وأنريل إنجن، والأردوينو، والروبوتات، وبايثون، وسي شارب، وسي بلس بلس، وتطوير الألعاب، وتطوير الويب، وتصميم واجهات المستخدم، والأمن السيبراني، وعلم البيانات.",
      },
      {
        topic: "courses",
        q: "هل أحتاج إلى خبرة سابقة لبدء دورة؟",
        a: "لا توجد حاجة لخبرة سابقة في مساراتنا التأسيسية. تبدأ كل دورة من المبادئ الأولى، ويتم تصنيف المتقدمين في المستوى المناسب بعد تقييم مهارات قصير.",
      },
      {
        topic: "registration",
        q: "كيف أسجل في دورة؟",
        a: "راسلنا على واتساب أو عبر صفحة التواصل مع اسم الدورة التي تهمك، أو أرسل لنا بريدًا مباشرة. سيتابع فريق القبول خلال 1-2 يوم عمل لتأكيد مقعدك.",
      },
      {
        topic: "registration",
        q: "هل يمكنني تغيير المسار بعد التسجيل؟",
        a: "نعم، خلال أول أسبوعين من الدفعة يمكنك تغيير المسار دون أي تكلفة إضافية، حسب توفر المقاعد.",
      },
      {
        topic: "certificates",
        q: "هل أحصل على شهادة بعد التخرج؟",
        a: "نعم. يحصل كل خريج على شهادة معتمدة من كوانتوم بالإضافة إلى ملف مشاريع تمت مراجعته يمكن مشاركته مع أصحاب العمل.",
      },
      {
        topic: "certificates",
        q: "هل شهادات كوانتوم معترف بها من أصحاب العمل؟",
        a: "شهاداتنا مدعومة بملف مشاريع تمت مراجعته وشبكة شركاء توظيف، وهو ما يوليه أصحاب العمل أهمية أكبر إلى جانب الشهادة نفسها.",
      },
      {
        topic: "schedule",
        q: "كم مدة الدورات؟",
        a: "تمتد معظم المسارات من 10 إلى 14 أسبوعًا بدوام جزئي، مع خيارات مكثفة بدوام كامل تضغط المنهج نفسه إلى 5-6 أسابيع.",
      },
      {
        topic: "schedule",
        q: "هل الحصص حضورية أم عبر الإنترنت أم كلاهما؟",
        a: "كلاهما. يُنصح بشدة بالحضور الشخصي لمسارات الأجهزة مثل الروبوتات والأردوينو للوصول إلى المختبر، بينما تتوفر مسارات الذكاء الاصطناعي والبرمجة وتطوير الألعاب بالكامل عبر الإنترنت مع جلسات إرشاد مباشرة.",
      },
      {
        topic: "fees",
        q: "كم تكلفة الدورات؟",
        a: "تختلف الرسوم حسب المسار والصيغة — تواصل مع فريق القبول لمعرفة الأسعار الحالية وأي عروض نشطة للدفعة.",
      },
      {
        topic: "fees",
        q: "هل تتوفر خطط دفع؟",
        a: "نعم، تتوفر خطط تقسيط شهرية لكل مسار، بالإضافة إلى منح دراسية حسب الحاجة للطلاب المؤهلين.",
      },
      {
        topic: "online",
        q: "ماذا أحتاج للتعلم عبر الإنترنت؟",
        a: "حاسوب محمول واتصال إنترنت مستقر كافيان لمعظم المسارات البرمجية. تتضمن مسارات الأجهزة عدة بدء تُشحن إليك كجزء من التسجيل.",
      },
      {
        topic: "online",
        q: "هل التعلم عبر الإنترنت فعال بقدر الحضور الشخصي؟",
        a: "تتبع الدفعات عبر الإنترنت المنهج نفسه مع جلسات إرشاد مباشرة، ومراجعات للأكواد والمشاريع، ودعم وظيفي — الصيغة تتغير، لكن الصرامة لا تتغير.",
      },
    ],
  },
  projects: {
    kicker: "٠٦ / أعمالنا",
    title: "مختارات من أعمالنا.",
    items: [
      {
        k: "greenhouse",
        name: "البيت الزراعي الذكي",
        tag: "إنترنت الأشياء · أردوينو",
        meta: "2025 · الأغوار",
        desc: "حساسات للتربة والمناخ تتولّى الري والتهوية تلقائيًا — ووفّرت 35% من استهلاك المياه.",
      },
      {
        k: "clinic",
        name: "منصة حجوزات العيادات",
        tag: "تطبيق ويب",
        meta: "2025 · عمّان",
        desc: "حجز مواعيد وتذكيرات ولوحة تحكم إدارية لعيادة متعددة الأطباء.",
      },
      {
        k: "vision",
        name: "عدّاد الزوار الذكي",
        tag: "رؤية حاسوبية",
        meta: "2024 · عمّان",
        desc: "كاميرا ذكية تعدّ الزوار لحظة بلحظة وتحدّد ساعات الذروة.",
      },
      {
        k: "chatbot",
        name: "مساعد الطلاب الذكي",
        tag: "روبوت محادثة",
        meta: "2024 · إربد",
        desc: "يجيب على أسئلة الطلاب حول الجداول والخدمات على مدار الساعة.",
      },
      {
        k: "robots",
        name: "روبوتات تتبّع الخط",
        tag: "تعليم",
        meta: "2025 · الزرقاء",
        desc: "برنامج روبوتات مدرسي — 40 طالبًا بنوا روبوتاتهم وتسابقوا بها.",
      },
    ],
  },
  why: {
    kicker: "٠٧ / لماذا Quantum",
    title: "أربعة أسباب، وإشارة واحدة.",
    items: [
      { t: "حلول متكاملة", d: "من الفكرة إلى الكود إلى العتاد — فريق واحد يتولّى كل شيء." },
      { t: "تدريب عملي", d: "كل دورة مبنية على مشاريع حقيقية تلمسها بيدك." },
      { t: "دعم حقيقي", d: "نبقى معك بعد التسليم، لا حتى الإطلاق فقط." },
      { t: "ذكاء اصطناعي عملي", d: "ذكاء يحلّ مشكلات فعلية، لا عروضًا شكلية." },
    ],
  },
  contact: {
    kicker: "٠٨ / تواصل معنا",
    title: "أرسل لنا إشارة.",
    sub: "لديك مشروع، أو سؤال عن منتج، أو ترغب بالانضمام إلى دورة؟ نردّ بسرعة.",
    name: "الاسم",
    email: "البريد الإلكتروني",
    message: "رسالتك",
    send: "إرسال",
    sent: "شكرًا لك! سنتواصل معك قريبًا.",
    viaWhatsapp: "أو أرسلها عبر واتساب",
    errName: "يرجى إدخال اسمك.",
    errEmail: "يرجى إدخال بريد إلكتروني صحيح.",
    errMessage: "أخبرنا بتفاصيل أكثر (10 أحرف على الأقل).",
    waHello: "مرحبًا كوانتوم لاب، أرغب في معرفة المزيد عن دوراتكم.",
    location: "عمّان، الأردن",
    labels: {
      whatsapp: "واتساب",
      phone: "الهاتف",
      email: "البريد",
      instagram: "إنستغرام",
      location: "الموقع",
    },
    follow: "تابع مختبرنا على إنستغرام",
    followSub: "مشاريعنا وورشاتنا وأحدث القطع — أولًا على إنستغرام.",
  },
  home: {
    marquee: [
      "برمجيات",
      "ذكاء اصطناعي",
      "أردوينو",
      "دورات",
      "إنترنت الأشياء",
      "رؤية حاسوبية",
      "روبوتات",
      "مواقع وتطبيقات",
    ],
    process: {
      kicker: "كيف نبني",
      title: "من فكرة صغيرة إلى نظام شغّال.",
      sub: "كل مشروع في كوانتم يمرّ بنفس الدائرة من خمس مراحل — فتعرف دائمًا ما الخطوة التالية.",
      steps: [
        { t: "نكتشف", d: "نسمعك ونزور الموقع ونفهم المشكلة الحقيقية قبل كتابة أي سطر." },
        { t: "نصمّم", d: "مخططات للواجهات والدوائر وخطة واضحة بالوقت والتكلفة." },
        { t: "نبني", d: "برمجة وتدريب ولحام على مراحل قصيرة — وتشوف التقدّم كل أسبوع." },
        { t: "نطلق", d: "تجربة على أرض الواقع، ثم تشغيل وتدريب فريقك على الاستخدام." },
        { t: "ندعم", d: "متابعة وتحديثات وفريق يرد عليك وقت ما تتصل." },
      ],
    },
    showcase: {
      kicker: "أعمال مختارة",
      title: "انبنت هون. وشغّالة هناك.",
      sub: "بعض الأنظمة التي صمّمناها وبرمجناها وركّبناها — وتعمل اليوم كل يوم.",
      all: "شوف كل المشاريع",
    },
    numbers: {
      kicker: "بالأرقام",
      title: "ست سنوات من الإشارة.",
      items: [
        { n: 500, s: "+", l: "طالب تدرّب معنا" },
        { n: 17, s: "", l: "دورة" },
        { n: 20, s: "+", l: "مشروع" },
        { n: 95, s: "%", l: "رضا الطلاب" },
      ],
    },
    voices: {
      kicker: "شو بيحكوا عنا",
      title: "أصوات من الدائرة.",
      items: [
        {
          q: "مسار الروبوتات والأردوينو غيّر تمامًا طريقتي في التعامل مع الهندسة — شعرت المختبرات وكأنني أعمل في شركة ناشئة حقيقية.",
          n: "رانيا مالك",
          r: "خريجة مسار الروبوتات",
        },
        {
          q: "انتقلت من الصفر إلى إطلاق نموذج أولي للواقع الافتراضي خلال اثني عشر أسبوعًا. الإرشاد هنا لا مثيل له.",
          n: "كريم طه",
          r: "خريج مسار الواقع الممتد والافتراضي",
        },
        {
          q: "برنامج الذكاء الاصطناعي في كوانتوم لاب صارم بقدر أي معسكر تدريبي رأيته — والدعم الوظيفي كان فعليًا مثمرًا.",
          n: "سارة لوند",
          r: "خريجة مسار الذكاء الاصطناعي",
        },
        {
          q: "مسار يونيتي وتطوير الألعاب حوّل فكرة مشروعي الجانبي إلى لعبة حقيقية ومكتملة.",
          n: "دانيال أوسي",
          r: "خريج تطوير الألعاب",
        },
        {
          q: "الأمن السيبراني هنا عملي منذ اليوم الأول — كنت أجري اختبارات اختراق حقيقية خلال الشهر الأول.",
          n: "نادية فارس",
          r: "خريجة الأمن السيبراني",
        },
      ],
    },
    outro: {
      words: ["كود.", "دوائر.", "ذكاء."],
      sub: "ثلاث تخصصات، ومختبر واحد. ادخل وتعرّف على الناس اللي ورا الإشارة.",
      btn: "تعرّف على المختبر",
    },
  },
  pages: {
    home: "الرئيسية",
    app: {
      tabs: { home: "الرئيسية", software: "البرمجيات", ai: "الذكاء", arduino: "أردوينو" },
      more: "المزيد",
      menu: "القائمة",
      language: "اللغة",
      quick: "تواصل سريع",
      call: "اتصال",
      close: "إغلاق",
    },
    lost: {
      title: "انقطعت الإشارة.",
      sub: "هذه الصفحة غير موجودة أو تم نقلها. خلّينا نرجّعك للدارة.",
      btn: "العودة للرئيسية",
    },
    next: "الصفحة التالية",
    loading: "جارٍ توجيه الإشارة",
    explore: {
      kicker: "استكشف Quantum",
      title: "سبعة عوالم، ومختبر واحد.",
      sub: "لكل جزء من Quantum صفحته الخاصة — اختر بابًا وادخل.",
      enter: "ادخل",
    },
    cta: {
      title: "عندك فكرة؟ خلّينا نوصّلها.",
      sub: "برمجيات، ذكاء اصطناعي، جهاز ذكي أو دورة — أخبرنا ماذا تريد أن تبني.",
      btn: "ابدأ مشروعك",
      alt: "راسلنا على واتساب",
    },
    about: {
      title: "مختبر تتحوّل فيه الأفكار إلى واقع.",
      sub: "من نحن، وما الذي يحرّكنا، ولماذا يثق بنا المبتكرون والشركات.",
      blurb: "قصتنا ورؤيتنا وسبب اختيار الناس للعمل معنا.",
      facts: [
        { n: 4, s: "", l: "تخصصات تحت سقف واحد" },
        { n: 6, s: "+", l: "سنوات من البناء" },
        { n: 15, s: "+", l: "مهندسًا ومدرّبًا" },
      ],
    },
    software: {
      title: "برمجيات تصل إلى الإطلاق.",
      sub: "مواقع وتطبيقات وأنظمة مخصّصة — مصمّمة للسرعة ومبنية لتدوم.",
      blurb: "مواقع وتطبيقات وأنظمة مخصّصة ولوحات تحكم.",
      facts: [
        { n: 70, s: "+", l: "موقعًا وتطبيقًا أُطلق" },
        { n: 99, s: "%", l: "جاهزية المشاريع المستضافة" },
        { n: 4, s: "", l: "خطوط خدمة أساسية" },
      ],
    },
    ai: {
      title: "ذكاء اصطناعي يشتغل فعلًا.",
      sub: "روبوتات محادثة ورؤية حاسوبية وتنبؤ — ذكاء عملي لمشكلات حقيقية.",
      blurb: "محادثة ورؤية حاسوبية وتنبؤ وأتمتة وذكاء طرفي.",
      facts: [
        { n: 25, s: "+", l: "نموذجًا ذكيًا قيد التشغيل" },
        { n: 5, s: "", l: "قدرات ذكاء اصطناعي" },
        { n: 24, s: "/7", l: "مساعدات لا تنام" },
      ],
    },
    arduino: {
      title: "ركن العتاد الإلكتروني.",
      sub: "لوحات وحقائب وحساسات ووحدات ذكاء اصطناعي — تعال شاهدها واسأل عنها وابنِ بها.",
      blurb: "لوحات وحقائب وحساسات ووحدات ذكاء متوفرة لدينا.",
      facts: [
        { n: 60, s: "+", l: "قطعة متوفرة" },
        { n: 24, s: "", l: "نوعًا من القطع" },
        { n: 4, s: "", l: "حقائب مميّزة" },
      ],
    },
    courses: {
      title: "تعلّم وأنت تبني.",
      sub: "مسار واضح من أول سطر كود حتى جهازك الذكي الخاص.",
      blurb:
        "17 دورة في الذكاء الاصطناعي والواقع الممتد والألعاب والأردوينو والبرمجة والويب والأمن.",
      facts: [
        { n: 500, s: "+", l: "متدرب" },
        { n: 17, s: "", l: "دورة" },
        { n: 7, s: "", l: "مسارات تعليمية" },
      ],
    },
    projects: {
      title: "أعمال تعمل على أرض الواقع.",
      sub: "أنظمة حقيقية تعمل في مزارع وعيادات ومحلات ومدارس في أنحاء الأردن.",
      blurb: "مشاريع حقيقية لمزارع وعيادات ومحلات ومدارس.",
      facts: [
        { n: 20, s: "+", l: "مشروع" },
        { n: 5, s: "", l: "مدن خدمناها" },
        { n: 35, s: "%", l: "توفير مياه في مشروع واحد" },
      ],
    },
    contact: {
      title: "خلّينا نحكي.",
      sub: "واتساب، اتصال، بريد، أو زرنا في المختبر — نردّ بسرعة.",
      blurb: "واتساب وهاتف وبريد وإنستغرام والموقع.",
      facts: [
        { n: 1, s: "س", l: "متوسط وقت الرد" },
        { n: 7, s: "", l: "أيام في الأسبوع على واتساب" },
        { n: 95, s: "%", l: "رضا الطلاب" },
      ],
    },
  },
  footer: {
    tagline: "مختبر تقني يبني البرمجيات والذكاء الاصطناعي والعتاد — ويعلّم مبتكري الغد.",
    explore: "استكشف",
    connect: "تواصل",
    rights: "جميع الحقوق محفوظة.",
    top: "العودة للأعلى",
  },
};

export const content = { en, ar };
